version: "3.8"

services:
  db:
    image: postgres:15
    container_name: sigl_postgres
    environment:
      POSTGRES_DB: sigl_db
      POSTGRES_USER: sigl_user
      POSTGRES_PASSWORD: sigl_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sigl_network

  backend:
    build: ./backend
    container_name: sigl_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sigl_db
      SPRING_DATASOURCE_USERNAME: sigl_user
      SPRING_DATASOURCE_PASSWORD: sigl_pass
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - sigl_network

  frontend:
    build: ./frontend
    container_name: sigl_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - sigl_network

volumes:
  db_data:

networks:
  sigl_network:
    driver: bridge
